filetype off
set rtp+=vader.vim
set rtp+=.
set rtp+=after
filetype plugin indent on
syntax enable

set grepprg=ag\ --vimgrep
set grepformat=%f:%l:%c:%m

let g:vjs_debug=1
let g:vjs_test_env=1

fun GetLastMessage()
  redir => msgs
  silent messages
  redir END
  return get(split(msgs, "\n"), -1, "")
endf

fun LogAllMessages()
  redir => msgs
  silent messages
  redir END
  Log msgs
endf

fun SortByLnum(a,b)
  return a:a.lnum > a:b.lnum ? 1 : -1
endf

fun GetQFListFiles()
  let qflist = getqflist()
  call map(qflist, {k,v -> {'fname': bufname(v.bufnr), 'lnum': v.lnum, 'text': v.text}})
  return sort(qflist, "SortByLnum")
endf

fun GetQFList()
  let qflist = getqflist()
  call map(qflist, {k,v -> {'lnum': v.lnum, 'text': v.text}})
  return qflist
  return sort(qflist, "SortByLnum")
endf

