filetype off
set rtp+=vendor/*
set rtp+=.
set rtp+=after
filetype plugin indent on
syntax enable

set grepprg=rg\ --vimgrep
set grepformat=%f:%l:%c:%m
set shiftwidth=2

let g:vjs_debug=1
let g:vjs_test_env=1

fun GetLastMessage()
  redir => msgs
  silent messages
  redir END
  return get(split(msgs, "\n"), -1, "")
endf

fun LogAllMessages()
  redir => msgs
  silent messages
  redir END
  Log msgs
endf

fun SortByLnum(a,b)
  return a:a.lnum > a:b.lnum ? 1 : -1
endf

fun GetQFListFiles()
  let qflist = getqflist()
  call map(qflist, {k,v -> {'fname': bufname(v.bufnr), 'lnum': v.lnum, 'text': v.text}})
  return qflist
endf

fun GetQFList()
  let qflist = getqflist()
  call map(qflist, {k,v -> {'lnum': v.lnum, 'text': v.text}})
  return qflist
endf

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = { 'javascript' },
  indent = {
    enable = true
  }
}
EOF
