#!/usr/bin/env bash
set -ex

test_file=${1:-test/**/*.vader}

if [ -z "$CI" ]; then
  cmd=nvim
else
  cmd=./squashfs-root/usr/bin/nvim
fi

if [ ! -d ./nvim-treesitter ]; then
  git clone https://github.com/nvim-treesitter/nvim-treesitter.git
  $cmd --headless -u ./test/vimrc -c 'TSInstallSync! javascript | q'
fi

if [ ! -d ./vader.vim ]; then
  git clone https://github.com/junegunn/vader.vim.git
fi

$cmd --headless -u ./test/vimrc -c "Vader! $test_file"
