#!/usr/bin/env bash

set -e

test_file=${1:-test/*.vader}

if [ -z "$CI" ]; then
  cmd=nvim
else
  cmd=./squashfs-root/usr/bin/nvim
fi

# TODO: fix tests on nvim
cmd=vim

$cmd -Nu ./test/vimrc -c "Vader! $test_file"
