version: 2
jobs:
   build:
     docker:
       - image: cimg/node:20.2.0
     steps:
       - checkout
       - run: sudo apt-get update
       - run: sudo apt-get install --yes git ripgrep
       - run: sudo npm install -g typescript-language-server typescript
       - run: sudo curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
       - run: sudo chmod +x nvim.appimage
       - run: sudo ./nvim.appimage --appimage-extract
       - run: sudo chmod -R a+rwx ./squashfs-root
       - run: ./run_tests
